### PR TITLE
Add ttf-mscorefonts-installer package

### PR DESCRIPTION
**Pull request by ddemidov**
See ev3dev/ev3dev#751.

Is this the correct place to add the package?

### CODE REVIEW

**Comment by dlech** [comment]
Yes, this is the correct place.

**Comment by dlech** [comment]
Do you still want to include this or are you going to stick with PIL fonts?

**Comment by ddemidov** [comment]
There is rhempel/ev3dev-lang-python#225, but that will only be released as 0.7.1. So if you want to create new image, then I guess `ttf-mscorefonts-installer` need to be included so that some fonts are available.

**Comment by dlech** [comment]
I would rather not include it if we are just going to remove it later.

**Comment by ddemidov** [comment]
That makes sense as well. I'll close this then and if anybody needs ttf fonts, they can install those by hand.

**Pull request closed without merging**
